// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content: string;
  filterButton: string;
  header: string;
  modActions: string;
  modInfo: string;
  modInfoText: string;
  modInfoTitle: string;
  modList: string;
  modRow: string;
  modRowInfo: string;
  modRowTitle: string;
  repoContent: string;
  repoHeader: string;
  root: string;
  searchBar: string;
  sidebar: string;
}
declare const cssExports: CssExports;
export default cssExports;
